### ISSUE TITLE
לינק השתנה

### ISSUE THREAD

**Issue by eyalmigd** [meirim-org/meirim#105]
פעם זה היה הלינק של התכנית למלון בוטיק בכיכר ביאליק ועכשיו זה הפך להיות משהו אחר ממנחמיה....

https://meirim.org/plan/?id=12522

**Comment by eyalmigd** [comment]
הוא ממשיך להשתנות, עכשיו הוא 
ברטעה - הסדרת דרך

**Comment by dortheimer** [comment]
done
