### ISSUE TITLE
תכנית שנשלחה פעמיים ולא ברור למה

### ISSUE THREAD

**Issue by eyalmigd** [meirim-org/meirim#107]
תכנית בית באר ברחוב הרצל נשלחה אלי ב5 לדצמבר וב30 לנובמבר - לא ברור לי למה אבל נראה לי שלא היה שינוי בסטטוס התכנית על פי בדיקה של התכנית באתר מנהל התכנון

**Comment by dortheimer** [comment]
נפתר
