### ISSUE TITLE
הוספת הערה בנוגע לתכניות בסמכות מקומית

### ISSUE THREAD

**Issue by eyalmigd** [meirim-org/meirim#113]
מכיוון שתכניות בסמכות מקומית נקלטות בשלב הקליטה הראשוני/כשהן עוברות תנאי סף
ויתר העדכונים שלהם לא נכונים / לא מדוויקים חשוב להוסיף הערה לגבי מידת העדכון שלהם 

גם בדף התכניות 
וגם במייל

כזה:

שימו לב! מכיוון שהוועדות המקומיות לא מדווחות בצורה אחידה אודות הסטטוס של התכניות בסמכותן אנחנו ממליצים לא להסתמך על סטטוס התכניות בסמכות מקומית (גם לא כמו שמופיע באתר "תכנון זמין") - למעט אישור. אם קיבלתם התראה על תכנית חדשה בסמכות מקומית זה אומר שהתכנית עברה "תנאי סף" וכנראה שהיא בהפקדה או תכף מופקדת. תשארו עירניים!

**Comment by GalGend** [comment]
שימו לב! זוהי תכנית המופקדת בסמכות מקומית. מכיוון שהוועדות המקומיות לא מדווחות בצורה אחידה אודות הסטטוס של התכניות בסמכותן אנחנו ממליצים לא להסתמך על סטטוס התכניות  (גם לא כמו שמופיע באתר "תכנון זמין") - למעט אישור. אם קיבלתם התראה על תכנית חדשה בסמכות מקומית זה אומר שהתכנית עברה "תנאי סף" וכנראה שהיא בהפקדה או תכף מופקדת. תשארו עירניים!
