### ISSUE TITLE
כשמוסיפים כתובת בטופס ההתראה חסר נוטיפיקישן

### ISSUE THREAD

**Issue by eyalmigd** [meirim-org/meirim#114]
משהו כזה:

קיבלנו את הבקשה שלך! את/ה מוזמן/ת להוסיף כתובת נוספת או לצאת מטופס ההתראות. אנחנו נעיר אותך כשתתקבל תכנית באזור המובקש.

**Comment by florpor** [comment]
cleaning old issues
