### ISSUE TITLE
להגדיל ליוזר של איל את ההתראות

### ISSUE THREAD

**Issue by eyalmigd** [meirim-org/meirim#118]
אני רוצה לקבל התראות לא רק בתל אביב 
אלא בכל הארץ
כדי שאם יש תכנית מעניינת אוכל לכתוב על זה פוסט בפייסבוק

אני יודע שזה לא באג 
יונתן אל תכעס
רק כדי שלא ילך לאיבוד

**Comment by florpor** [comment]
done
