### ISSUE TITLE
חסר כפתור התנתק בטופס ההתראות

### ISSUE THREAD

**Issue by eyalmigd** [meirim-org/meirim#122]
בטופס ההתראות יש כפתור התחברות אבל אין מצב שהגעתי לשם אם לא התחברתי
ולכן הכפתור התחברות מבלבל.

הייתי מוריד את כפתור ההתחברות ומחליף אותו בכפתור התנתק שמחזיר אותי לעמוד הראשי

**Comment by GalGend** [comment]
resolved with new version
