### ISSUE TITLE
להוסיף נוטיפקיישן להודעות

### ISSUE THREAD

**Issue by eyalmigd** [meirim-org/meirim#125]

**Comment by GalGend** [comment]
גל ויונתן:

דרך מימוש : שומרים סטייט של משתמש עבור תוכנית
דיפולט: למשתמש אין עניין
אם המשתמש צופה / מדרג/ מגיב

API:
POST /plan/:id/subscribe 
DELETE /plan/:id/unsubscribe

במייל:

- [ ] להוסיף למייל של התראה אפשרות לעקוב אחרי תוכנית זאת

- [ ] להצייג את הסטטיס של המשתמש בעמוד התוכנית

- [ ] במיל- במקום כפתור ״צפייה״- ״מה דעתך על התוכנית״

- [ ] כאשר משתמש מגיב / פותח - לרשום אותו כעוקב

- [ ] כאשר משתמש מגיב- לשלוח הודעה לכל המתעניינים

- [ ] להציג בעמוד תוכנית כמה אנשים עוקבים אחריה

**Comment by florpor** [comment]
cleaning old issues
