### ISSUE TITLE
לשנות ולהרחיב אופן הגדרת מרחב התראות

### ISSUE THREAD

**Issue by eyalmigd** [meirim-org/meirim#133]
משתמשים מהפריפריה טוענים שרדיוס של 5 קילומטר איננו מספיק 
וגם
פעילה ממרכז המועצות האזוריות מבקשת לקבל התראות בכל "מועצה אזורית עמק זבולון"

הייתי ממליץ להגדיל את הרדיוס לעד 10 ק"מ
ולהוסיף אפשרות להגדיר מרחב תכנון (יש שכבה בסרוויס של מנהל התכנון ככל שאני יודע) כאזור התראה

**Comment by GalGend** [comment]
resolved
