### ISSUE TITLE
תיקון בכניסה למסך ההתראות

### ISSUE THREAD

**Issue by eyalmigd** [meirim-org/meirim#134]
אם אני לוחץ על כפתור התראות בדף השער ואני לא מחובר אז אני מועבר למסך בו אני צריך להזין מייל וסיסמא. אחרי שהזנתי אותם ולחצתי אישור אני עובר בחזרה לשער במקום לטופס ההתראות. זה מבלבל

**Comment by GalGend** [comment]
resolved with v3 version
