### ISSUE TITLE
כפתור מעירים לא מוביל לדף שער במידה ואני מחובר אלא לדף תכניות

### ISSUE THREAD

**Issue by eyalmigd** [meirim-org/meirim#135]

**Comment by GalGend** [comment]
עשינו את זה בכוונה, מתוך הבנה שאין למשתמש מה לעשות בעמוד הרשמה אם הוא כבר מחובר
הרעיון מאחורי זה- עמוד תוכניות יהיה העמוד הראשי
@eyalmigd

**Comment by dortheimer** [comment]
נפתור את זה בגרסה הבאה.
