### ISSUE TITLE
לשנות טקסט בעמוד השער

### ISSUE THREAD

**Issue by eyalmigd** [meirim-org/meirim#136]
זה הטקסט החדש:

מערכת ההתראות שלנו מאגדת במקום אחד את כל התכניות מכל ועדות התכנון ותשלח לכם התראה 
למייל לפי העדפה גיאוגרפית ובזמן אמת בכל פעם שסטטוס התכנית ישתנה. מהיום תוכלו לעקוב בקלות אחרי השינויים ליד הבית שלכם.

**Comment by dortheimer** [comment]
Resolved

**Comment by dortheimer** [comment]
Resolved
