### ISSUE TITLE
לשנות תיזמון שליחת התראות

### ISSUE THREAD

**Issue by eyalmigd** [meirim-org/meirim#149]
כך שההתראה תשלח בסמוך למועד העדכון ולא בשעות לא סבירות בערב/לילה ולא בשבת (לבקשת (המשתמשים

**Comment by dortheimer** [comment]
אתה מתכוון שההתראה לא תשלח בסמוך למועד העדכון, אלא בשעות היום.
הרי ההתראה נשלחת מכיוון שהעדכון בקוים כחוליםמתבצע בשעות לא סבירות.

**Comment by eyalmigd** [comment]
לא בהכרח מדויק. נתונים שעודכנו ב17 במהלך היום נשלחו למשתמשים ביום שישי ה19 בערב/לילה

בכל מקרה, אם זה לא היה ברור - הכוונה היא שהמערכת תשלח את ההתראות בסמיכות האפשרית למועד העדכון ובתנאי שההתראה לא תשלח בלילה או בשבת
