### ISSUE TITLE
New Single Plan - with Sliding Up Panel

### ISSUE THREAD

**Issue by GalGend** [meirim-org/meirim#175]
Hi,

I am working on a new single plan page with two modes- one for mobile.

In mobile mode, it should have a sliding up panel, with a "google maps" look :

<img width="188" alt="Screen Shot 2020-02-11 at 17 27 09" src="https://user-images.githubusercontent.com/22238092/74261881-d0ad3e80-4cf3-11ea-86bd-89bf9ae0bbf4.png">

I found a component that behaves similarly, however it typescript compilation, which I did not succeed to configure the Babel.

I thought to just the compiled version of the package, called 'rn-sliding-up-panel' and to use it as a component.

I set up a working mini app of the package, could someone please help me with extracting its complied file?

https://3440ox733m.csb.app/

**Comment by muamichali** [comment]
@GalGend  would this component do what you want? https://reactjsexample.com/a-very-simple-resizable-panel-as-a-react-component/

**Comment by GalGend** [comment]
@muamichali I set up a sandbox with how I vision it to be (on mobile mode).
https://kdy6q.csb.app/

 I just need to understand how to manually change the TS configuration file of the 'rn-sliding-up-panel' to js

Inspiration is from Zillow 
<img width="177" alt="Screen Shot 2020-02-12 at 21 20 27" src="https://user-images.githubusercontent.com/22238092/74378283-96b86700-4ddd-11ea-963f-1cdd693fc1e1.png">

(https://www.zillow.com/homedetails/1015-Wilcox-Ave-1-Bronx-NY-10465/2081055775_zpid/)
