### ISSUE TITLE
User registration form

### ISSUE THREAD

**Issue by florpor** [meirim-org/meirim#218]
New registration form with the new fields - name, profile type, url and about me.
No photo upload yet.

**Comment by jbesraa** [comment]
this is a front end issue isnt?
in terms of design, I guess I'm following the current input design. 
what about the profile type input though? this is a dropdown I guess, should I use a dropdown from MUI?

**Comment by florpor** [comment]
yes this is the frontend part of the new registration flow.
sadly design is not final yet.. i'll let you know as soon as it is.
yes, for the profile type input you can use material ui's select component.
