### ISSUE TITLE
Issues in new Plan page

### ISSUE THREAD

**Issue by jbesraa** [meirim-org/meirim#272]
- [x] Like + Add Comment buttons are not aligned in bottom comment

<img width="830" alt="Screen Shot 2020-12-22 at 20 49 51" src="https://user-images.githubusercontent.com/21229375/102922777-3ed79b80-4497-11eb-8105-286bbfd6ae8f.png">

**Comment by jbesraa** [comment]
Panel are not in the right order

![Uploading Screen Shot 2020-12-23 at 10.21.41.png…]()

**Comment by jbesraa** [comment]
- [ ] input doesn't cleanup after sending comment
- [ ] no logic implement for not logged users when clicking on like/send message

**Comment by GalGend** [comment]
- [ ] Charts crashes page on resize- (try to resize https://stg.meirim.org/plan/100)

- [ ] Colors of the charts- we can make them green/ purple/ orange/  other colours according to the theme

@jbesraa @nadavsofi

**Comment by florpor** [comment]
- [ ] the "want-to-get-notified" banner register button should open the register modal (currently opens a message box saying "registration")
- [ ] plan map should allow zooming and panning
- [ ] comment and opinion should be limited to 1200 characters
- [ ] desktop back button next to the city name does not exist
- [ ] mobile back button does exist but does not navigate back

**Comment by nadavsofi** [comment]
> Panels are not in the right order
> 
> <img alt="Screen Shot 2020-12-23 at 10 22 39" width="469" src="https://user-images.githubusercontent.com/21229375/102975459-ca3d4500-4508-11eb-9970-e7f471b88a40.png">



> * [ ]  Charts crashes page on resize- (try to resize https://stg.meirim.org/plan/100)
> * [ ]  Colors of the charts- we can make them green/ purple/ orange/  other colours according to the theme
> 
> This is an issue with the `react-charts` package. We solved that issue previously by limiting the size of the chart div to 450px, see [this commit](https://github.com/meirim-org/meirim/commit/efc4801841e6af3ef837ad0402fa588f23ad55ee)
> @jbesraa @nadavsofi

**Comment by jbesraa** [comment]
- [ ] להחליף את הסדר של סוגי חוות הדעת: "הצעה לשיפור", "ביקורת", "חוות דעת כללית"

- [ ] אין הגבלה על מספר התווים לתגובה/חוות דעת. קבענו לדעתי 1200. קריטי 

- [ ]  הבאנר הסגול של "רוצים לקבל התראה כשתוכנית מתקדמת" עדיין מופיע למשתמש מחובר, למרות שהוא צריך להופיע רק למשתמשים לא מחוברים.
- [ ] טאבים - דסקטופ -  לא נשארים  sticky כשגוללים למטה, למרות העיצוב והאיפיון. מה שאמור להיעלם זה רק שם התוכנית, בעוד "תקציר", "חוות דעת" "מידע תכנוני" ושלושת הכפתורים צריכים להישאר דביקיים, או לפחות להופיע בזמן גלילה מעלה (אפשר לדבר על המורכבות של זה מול זה, ולהחליט מה לפתח). לא לפתח כרגע.


- [ ] עיצוב - חסר הקו האפור שמפריד בין הטאב (תקציר, חוות דעת וכו') לבין התוכן של הטאב

- [ ] עיצוב - הפונט של הטאבים  (תקציר, חוות דעת וכו') צריך להיות פונט px16
- [ ] באנר הרשמה - לא מקפיץ Flow הרשמה קריטי
- [ ] דסקטופ: חסר חץ אחורה ליד שם העיר שמחזיר לתוצאות החיפוש / עמוד תוכניות. במובייל החץ מופיע אבל לא עובד (לא מחזיר למסך התוכניות) קריטי
- [ ] המפה שהשתמשו בה היא המפה הסטטית מכרטיסיית התוכניות במקום המפה של המיקום - שמאפשרת לעשות זום ו- panning 
- [ ] הפוליגון לא מופיע ע"ג המפה. הוא מופיע רק אחרי טעינה נוספת של הדף. 
- [ ] לחיצה על "מסמכי התוכנית באתר הממשלה" - כרגע לא עושה כלום, אבל התנהגות אמורה להיות לפתוח טאב חדש בדפדפן.
- [ ] תגובות - כל סוג חוות דעת שנבחר מופיע כ"ביקורת" ב UI, במקום לפי הסוג ("חוות דעת כללית/הצעה לשיפור/ביקורת) קריטי
- [ ] התגובות לא מקבלות newline. צריך לתת להן newline ו Linebreak כדי שתהיינה קריאות

- [ ] הספירה של מספר חוות הדעת צריכה להיות גם על חוות הדעת וגם על התגובות.
- [ ] מובייל - חץ אחורה מתוך הטופס של הוספת חוות דעת אל עמוד חוות הדעת לא עובד. הטופס הזה הוא dead end כרגע. קריטי 
- [ ] דף התוכנית במובייל נטען עם פוקוס על אמצע הדף ולא עם הכותרת.
- [ ] סדר רכיבים בטאב התקציר: מיקום צריך להיות מעל הבאנר של "רוצים לקבל התראה".

**Comment by florpor** [comment]
- [ ] אם מנסים לשמור חוות דעת או תגובה ריקות מקבלים הודעת שגיאה במקום לבקש קלט מהמשתמש

**Comment by nadavsofi** [comment]
> * [ ]  Charts crashes page on resize- (try to resize https://stg.meirim.org/plan/100)
> 
> @GalGend We tried and couldn't reproduce the resize bug, please send us screenshots
> 
> * [ ]  Colors of the charts- we can make them green/ purple/ orange/  other colours according to the theme
> 
> This is an issue with the `react-charts` package. We solved that issue previously by limiting the size of the chart div to 450px, see [this commit](https://github.com/meirim-org/meirim/commit/efc4801841e6af3ef837ad0402fa588f23ad55ee)
> @jbesraa @nadavsofi

**Comment by jbesraa** [comment]
- [ ] הנראות active של כותרות הטאבים נמחקה

- [ ]  הוספת חוות דעת במובייל מקריסה את

**Comment by florpor** [comment]
- [ ] במובייל בגלילה של עמוד תוכנית למטה עד הסוף חלק ממטרות התוכנית מוסתרות על ידי הכפתורים בתחתית
- [ ] במובייל כשגוללים את החלק עם המפה כפתורי הזום וה-attriubtion מוצגים מעל ה-navbar (יש להם z יותר גבוה). אפשר לראות גם בעמוד רשימת התוכניות ששם העיר מוצג מעל ה navbar
- [ ] במובייל עמוד תוכנית נגלל קצת גם לצדדים

**Comment by GalGend** [comment]
- [ ] שיתוף בווטספ שולח לינק ללא קישור לתוכנית עצמה
![image](https://user-images.githubusercontent.com/22238092/103342762-06d1e900-4a93-11eb-86fd-3912371fc626.png)

**Comment by florpor** [comment]
closing this as the main pr is now merged. will create separate issues for enduring specific issues
