### ISSUE TITLE
Unsubscribe backend implementation.

### ISSUE THREAD

**Issue by dortheimer** [meirim-org/meirim#29]
1. Generate token in alert model: 
token = alert->unsubscribeToken(person)
encrypts person_id, email and alert_id and returns the token.

2. Add unsubscribe link to the alert email: points to front-end route /alert/unsubscribe/$token

3. Implement DEL /alert/$token route that will remove the alert.

**Comment by lilachritter** [comment]
Hey @dortheimer,
A few questions:

1. How do I create a new alert? When I try localhost:3000/alert/ (after login) and enter some random address to the body, I get 
`Error: ER_SP_DOES_NOT_EXIST: FUNCTION meirim.ST_GeomFromGeoJSON does not exist`
Is there some kind of validation for addresses that can be used for alerts?

2. Creating a token form more then one param, I see in person modal `resetPasswordToken` that the convention is seporating them with underscore? 

3. DEL implementaitoan for alert - should remove the record from db altogether or some kind of soft delete?

**Comment by dortheimer** [comment]
1. Can you share the body of the request?
2. The token is generated and decoded in the back-end, the front-end should not care about how to decode it.
3. The delete method is already implemented in the back-end.
