### ISSUE TITLE
add share on facebook support to plan and tree permit share windows

### ISSUE THREAD

**Issue by florpor** [meirim-org/meirim#349]
Currently only share on WhatsApp is available. add an additional share on Facebook option.

- [ ] Make sure preview metadata is displayed on the post itself. 

- [ ] Also, The microcopy of the share text should be different for Whatsapp and Facebook, not like 'רשיון כריתה שאולי יענין אותך' but 'רשיון כריתת עץ חדש ברמת גן'. 

Also, the map of the geolocation as a preview image

![image](https://user-images.githubusercontent.com/22238092/117545864-48216900-b030-11eb-8916-b5efec4f8a31.png)

**Comment by yaelal** [comment]
e.g 
<a href="https://www.facebook.com/sharer/sharer.php?u=example.org" target="_blank">
  Share on Facebook
</a>
Documentation can be found at https://developers.facebook.com/docs/reference/plugins/share-links/

**Comment by yaelal** [comment]
pr https://github.com/meirim-org/meirim/pull/581/files

**Comment by yaelal** [comment]
![image](https://user-images.githubusercontent.com/9642870/202293083-0de73c13-6c4c-45fe-a647-acb5925b13c8.png)

notice will not work with localhost url

**Comment by yaelal** [comment]
@GalGend can we close this?

**Comment by yaelal** [comment]
closed by #581
