### ISSUE TITLE
Tags DB

### ISSUE THREAD

**Issue by GalGend** [meirim-org/meirim#369]
Hi,

This task stands for creating tag tables in DB. It is required before backend functionality of tags. See proposed design [here](https://docs.google.com/presentation/d/1zlAGXRPWSy6C1LjmBDCl1IwKa8953pt2DwBQ5-93XAw/edit?usp=sharing)

- [x] Create a tag DB table migration, to include the following fields:
id | integeer
parent_id | integer, Key to tags from this table
display_name | text
score | Integer, default 0
is_super_tag | Boolean
is_stand_alone | Boolean
display_tooltip | text

- [x] Create a tag DB model with the same fields

- [x] Create a DB plan_tag model, that would represent a plan's tags. Make sure it populates a plan (association table).
Include the following fields:
id | integer
tag_id | FK to tags
plan_id | FK to plans
display_score | Integer, default 1
created_by_ data_rules | Text in list/json format
created_by_child | Boolean, default FALSE
child_ss_standAlone | Boolean, default&nbsp; False
creation_date | date/time

- [x] Add tags as a field of plans, populating it from this table

**Comment by GalGend** [comment]
Hi @TomerMe2 @muamichali Please update status of this task

**Comment by muamichali** [comment]
I think we can close this issue. Everything here is done. 

But please note that the crawler still needs to call this code.
