### ISSUE TITLE
Save Plan Status

### ISSUE THREAD

**Issue by GalGend** [meirim-org/meirim#372]
The exciting plan status functionality :)

- [ ] Add a new table to the DB, called `plan_status`. This should have the following fields:

id | string 
plan_id | FK to plans
status_text | string
date | datetime
description (פירוט) |  string

- [ ] Create a new job, that crawls plan stauses for all  plans that are not approved, every day. This should use the following (new) scrapper function: 

- [ ]  Add  a new fetchStatus function (at `mavat/status) that receives a  MAVAT URL and checks its statuses. save the *new* statuses to DB. (A new status is a status that is not similar by name or date to already existing statuses (both together are unique, while there could be 2 different statuses with the same name and/or dates). This should support adding multiple statuses at a time.

**Comment by drorgivton** [comment]
@GalGend check out this commit by Mor https://github.com/meirim-org/meirim/commit/6285746fa028ffcd0b931db8d6dc0cc7b564fd60

**Comment by GalGend** [comment]
Hi @TomerMe2 @muamichali Please update status of this task

**Comment by drorgivton** [comment]
@gruppin moving this to Done. Good job :)
