### ISSUE TITLE
Plan status API

### ISSUE THREAD

**Issue by drorgivton** [meirim-org/meirim#376]
related to #372 

On the plan page, we want to display the plan progress, using this  UI (yet, this task is only about server-side).

<img width="696" alt="image" src="https://user-images.githubusercontent.com/22238092/179421270-ba3784ad-f64a-4855-b5cf-dd857046fd01.png">

**This task is to add a "plan status" end point, and to display its status on the plan page.**

This task also includes the logic of creating a status "pipeline",  for a plan.

- [] add a `plan/<plan_id>/status` endpoint that returns the status pipeline (see below) for a plan.  the response should be of the following schema:``` [{"stepId":1, "name":"על שולחן הועדה", "date":"12/12/12", "current":"false", "completed":"true", "description":"this is an important step", icon }, {stepId:2 .....}, {stepId:3 .....}, {stepId:4 .....}]```.
See [this doc](https://docs.google.com/document/d/14I29CwyZJfSfw6U5ZObbZktCDol0dvCvFRb09spbUsY/edit#) for example JSON for different kinds of plans (need to add plan with step id 0)

- [ ] The model to create the response from `plan_status_change`, that is already in the DB. For each row in the plan_status_change , translate the status name using the mapping on this [link ](https://docs.google.com/spreadsheets/d/12zCzy_kNmPItxLnSXcaKctW_FgIaGYylHhqppFXEwxY/edit#gid=0) to a new mapped status. The mapping also shows which stepId it belongs to.

~~This can be achieved by saving all statuses, hardcoded in a file.~~ EDIT 8/8: Can use the existing status table for this mapping, it's ok to add columns there. New backoffice functionality in the works will enable edits to the data there. 

- [ ] Rules for creating the response

- the default of the response is to return 4 steps (1,2,3,4).
- Set the date in the response using the earliest (oldest) date of each mapped status 
- Steps that have no matching line in the `plan_status ` table (have not been completed yet) will have a null date, current:`false `and completed:`false`.
- Set the the latest step which has a date to current:`True` (so that only the last step is shown as active in the UI)
- If one of the plan statuses is `אחר` or there is no plan_status table, set stepId: 1 to completed:True and Current:True, and the rest of the steps to completed:false and current:false
- If the plan type (סוג תוכנית) = `הודעה לפי סעיף 77 ו 78 לחוק התכנון והבניה`, add a stepId:0, set to date: plan.createddate, completed:true, current:true, and all other steps to false for both.

**Comment by drorgivton** [comment]
@GalGend you next focus after digest

**Comment by drorgivton** [comment]
@gruppin  please acknowledge ownership on this task.. or assign back to me if you can't take now. Thanks:)

**Comment by GalGend** [comment]
resolved, PR merged
