### ISSUE TITLE
Add plan_area_changes Table

### ISSUE THREAD

**Issue by TomerMe2** [meirim-org/meirim#403]
We are using plan_area_changes table for research for quite some time. We want to add it to our backend now, in order to make tags with ease.
This issue is about adding the table and migrating the current plans into this table.

The structure of this table should be:
```
    CREATE TABLE `plan_area_changes` (
    `id` int unsigned NOT NULL AUTO_INCREMENT,
    `plan_id` int NOT NULL,
    `usage` text,
    `measurement_unit` text,
    `approved_state` text,
    `change_to_approved_state` text,
    `total_in_detailed_plan` text,
    `total_in_mitaarit_plan` text,
    `remarks` text,
    PRIMARY KEY (`id`),
    KEY `plan_area_changes_plan_id_foreign` (`plan_id`),
    CONSTRAINT `plan_area_changes_plan_id_foreign` FOREIGN KEY (`plan_id`) REFERENCES `plan` (`id`)
)
```

Python code that does the migration is attached. Its logic should be implemented in JS.
[create_plan_area_changes.zip](https://github.com/meirim-org/meirim/files/6850468/create_plan_area_changes.zip)

**Comment by GalGend** [comment]
@muamichali @TomerMe2 please update status of this task

**Comment by TomerMe2** [comment]
> @muamichali @TomerMe2 please update status of this task
We can close this issue.
Not that we need to make the crawler call this code.
