### ISSUE TITLE
Monitor Plan + Tree Fetch

### ISSUE THREAD

**Issue by GalGend** [meirim-org/meirim#411]
We should monitor that we get new plans + trees on daily basis.

**Comment by GalGend** [comment]
@gruppin Can you please add the tree link to monitor?

**Comment by Sund3** [comment]
`https://www.gov.il/BlobFolder/guide/pro_felling_trees/he/forestry_and_trees_falling_Befor_galil_golan.xls
https://www.gov.il/BlobFolder/guide/pro_felling_trees/he/forestry_and_trees_falling_after_galil_golan.xls
https://www.gov.il/BlobFolder/guide/pro_felling_trees/he/forestry_and_trees_falling_Befor_amakim_galil_gilboa.xls
https://www.gov.il/BlobFolder/guide/pro_felling_trees/he/forestry_and_trees_falling_after_amakim_galil_gilboa.xls
https://www.gov.il/BlobFolder/guide/pro_felling_trees/he/forestry_and_trees_falling_befor_merkaz-sharon.xls
https://www.gov.il/BlobFolder/guide/pro_felling_trees/he/forestry_and_trees_falling_after_merkaz_sharon.xls
https://www.gov.il/BlobFolder/guide/pro_felling_trees/he/forestry_and_trees_falling_Befor_merkaz_shfela.xls
https://www.gov.il/BlobFolder/guide/pro_felling_trees/he/forestry_and_trees_falling_after_merkaz_shfela.xls
https://www.gov.il/BlobFolder/guide/pro_felling_trees/he/forestry_and_trees_falling_Befor_jerusalem.xls
https://www.gov.il/BlobFolder/guide/pro_felling_trees/he/forestry_and_trees_falling_after_jerusalem.xls
https://www.gov.il/BlobFolder/guide/pro_felling_trees/he/forestry_and_trees_falling_Befor_darom.xls
https://www.gov.il/BlobFolder/guide/pro_felling_trees/he/forestry_and_trees_falling_after_darom.xls
https://www.gov.il/BlobFolder/guide/pro_felling_trees/he/forestry_and_trees_falling_Befortashtiot.xls
https://www.gov.il/BlobFolder/guide/pro_felling_trees/he/forestry_and_trees_falling_aftartashtiot.xls
https://www.gov.il/BlobFolder/guide/pro_felling_trees/he/forestry_and_trees_falling_befor_haifa.xls
https://www.gov.il/BlobFolder/guide/pro_felling_trees/he/forestry_and_trees_falling_after_haifa.xls
https://www.gov.il/BlobFolder/guide/pro_felling_trees/he/forestry_and_trees_falling_before-telaviv.xls
https://www.gov.il/BlobFolder/guide/pro_felling_trees/he/forestry_and_trees_falling_after-telaviv.xls
https://www.gov.il/BlobFolder/guide/pro_felling_trees/he/forestry_and_trees_falling_trees_befor.xlsx
https://www.gov.il/BlobFolder/guide/pro_felling_trees/he/forestry_and_trees_falling_trees_after.xlsx`

files look problematic on the uptime robot, will return to this
