### ISSUE TITLE
Develop Merchav Video page

### ISSUE THREAD

**Issue by GalGend** [meirim-org/meirim#432]
Following design task #430 

- [ ] The page should support displaying a list of videos, and a playing video.

[*** PLEASE REVIEW THIS PROTOTYPE WEBSITE ***](https://www.figma.com/proto/za4s6kKXMHh0X3URWVpXg1/Meirim-(Lishay)---October-2021?node-id=6500%3A94711&scaling=scale-down&page-id=6252%3A92398&starting-point-node-id=6500%3A94711)

This page includes adding a new page to out website- called Urban Planning (תכנון עירוני).
The page will display a header with general info about the course, and a list of videos.

Each video has a URL (youtube URL), a name, a presenter, a description, and duration.
On pressing a video, it should become the "playing video"

- [ ] Add a link at topbar for this page

- [ ] Add a config page for the videos (JSON/ JSX exporting the video list), where videos are configurable, and not hard-coded. Details for each video should include: title , description, duration (as text), presenter (text), youtube video id, id. Therefore, we should be able to manage the video list without touching the main video page.

- [ ] **Browse mode**The video page should display the list of the videos; page should be responsive and display video title (limited to 1 line), presenter (limited to 2 lines), video preview, video duration, and description 

- [ ] **Watch mode:** On clicking a video, a modal should open with the video at theatre mode. 

- [ ] Develop a banner, that explains about the course, and should be displayed in the watch mode.

- [ ] Responsiveness requirements: fully responsive. Mobile view attached as well.

Link to Figma design: https://www.figma.com/file/za4s6kKXMHh0X3URWVpXg1/Meirim-Lishay-October-2021?node-id=6252%3A92398

![image](https://user-images.githubusercontent.com/22238092/137528633-3828c602-3ecd-4bc8-bf0b-c0cabf886590.png)

![image](https://user-images.githubusercontent.com/22238092/137528474-eb9c9a09-a218-4ce9-afa0-5d83899bdc1c.png)

**Comment by drorgivton** [comment]
@GalGend can I close this task?

**Comment by GalGend** [comment]
merged
