### ISSUE TITLE
Poptin implementation

### ISSUE THREAD

**Issue by drorgivton** [meirim-org/meirim#434]
- Add to the home page ( stg in first phase) 
- should be configured so that popups can be shown only to users coming from specific referrer Params
- use this popup for testing  `<script id='pixel-script-poptin' src='https://cdn.popt.in/pixel.js?id=16fdb15730bc1' async='true'></script> `

**Comment by GalGend** [comment]
Hi Romi, as discussed I'll deploy the PR to Stg. can close this task for now

**Comment by GalGend** [comment]
resolved
