### ISSUE TITLE
Set up a new Uptime robot env

### ISSUE THREAD

**Issue by drorgivton** [meirim-org/meirim#436]
We need to create a new Uptime robot environment, that will be managed by the new meirim domain.
I sent @Sund3 the credentials by Whatsapp 2 weeks ago.

The setup contains the following subtask:

- [x] Add a slack integrtion, to the `#alert` channel. (interval of once every 10 mins)
- [x] Add an email integration, notifying Eyal's email. `ceo@meirim.org`

- [x] Add a monitor to the main website at `meirim.org`

**Comment by Sund3** [comment]
Done :)
