### ISSUE TITLE
Auto Email - Text issues

### ISSUE THREAD

**Issue by chechiktomer** [meirim-org/meirim#46]
Change text on Email:

https://drive.google.com/drive/folders/1-_eZxTmaEX1pDFs8saXR8oI09XQippJJ

**Comment by eyalmigd** [comment]
כותרת: "מעירים" - אימות כתובת דוא"ל

שלום X, אנחנו במרחק צעד אחד מלהפוך את מערכת היחסים ביננו לרשמית. 
אנא אמת/י את כתובת הדוא"ל באמצעות לחיצה על הקישור המצורף. מיד לאחר מכן תועבר/י לטופס בו תכל/י להגדיר את התחום בו תקבל/י התראות על תכנית בסמכות מקומית ומחוזית. 

www.blablalbla.com

תכף מתחילים, 
החברים "ממעירים".

לוגו
_______________________________________________________________________

כותרת: ברוכים הבאים ל"מעירים"

שלום X, הרשמתך נקלטה במערכת, אנחנו שמחים שהצטרפת אלינו.

אז מה אנחנו עושים?


אנחנו מפתחים מערכת התראות למידע תכנוני ועידוד אקטיביזם עירוני - בשלב זה המערכת כוללת תכניות בסמכות מקומית ומחוזית בלבד.  מידי לילה, המערכת מתעדכנת, ומתריאה על ישויות חדשות כפי שהוזנו לשרת. המערכת נמצאת בהרצה ראשונה ועל כן, השימוש במידע נמצא באחריות המשתמשים. מבדיקות שכבר עשינו גילינו שיש פערים בקצב הזנת המידע ודיוק המידע בין תכניות ובין ועדות. נשמח אם תעזרו לנו לפקוח עיניים ולעמוד על הפערים וההבדלים בין המחוזות השונים. נהיה זמינים בעמוד הפייסבוק שלנו ובמייל 


info@meirim.org

לחיי תכנון לכולם, 
ותודה שהצטרפת,
החברים "ממעירים".

לוגו
_______________________________________________________________________

כותרת: "מעירים" -  תזכורת סיסמא 

שלום X, הסיסמא שלך היא: XYZ


החברים "ממעירים".

לוגו
________________________________________

**Comment by dortheimer** [comment]
Resolved
