### ISSUE TITLE
Design 3rd map toggle for plan page

### ISSUE THREAD

**Issue by drorgivton** [meirim-org/meirim#463]
The plan page has a 2d map.

We want to show a toggle to change the view into 3rd, and back.

The 3rd is an implementation of[ simplex mapping. ](https://simplex-smart3d.com/ces/kono/app/)

the area of the plan will show as a 3rd "fence". Sometimes, an entire 3rd model will load (some plans have a 3rd model, some don't)

**Comment by Lishaysokol** [comment]
@GalGend Do we want a button to enlarge the map to a full window? `element.requestFullscreen()`

I think the experience could be better instead of viewing 3d map just on half of the page

**Comment by GalGend** [comment]
This is what we discussed on Monday, we agreed to support the full screen mode

**Comment by drorgivton** [comment]
done - FIGMA LINK https://www.figma.com/file/za4s6kKXMHh0X3URWVpXg1/Meirim-(Lishay)---April-2022?node-id=6708%3A95236
