### ISSUE TITLE
Landing Page - Our Partners section

### ISSUE THREAD

**Issue by chechiktomer** [meirim-org/meirim#47]
Pictures size needs to be the same.

Clicking picture needs to direct to their sites.

Updated pictures size and links on:
https://drive.google.com/drive/folders/12ln5pR-G8Pkn3_N0F8gx8OWCprMNjkWU

Please note that the pictures are double the size it needs to be (resize 50%)

**Comment by BlueHotDog** [comment]
@chechiktomer If we need pictures to be the same size, they need to be CUT the same size.. it's super easy and it'll make our life 10x better.

**Comment by chechiktomer** [comment]
@eyalmigd @annlillman 
OK?
