### ISSUE TITLE
Research Backoffice tools (DB client)

### ISSUE THREAD

**Issue by drorgivton** [meirim-org/meirim#491]
Gievn that we migrate to RDS, we would like to have the option to browse and manage data in non-tech way.
(Beside using AWS x-ray)

**Comment by drorgivton** [comment]
@Sund3 Hi! any updates?

**Comment by Sund3** [comment]
@drorgivton I remember @raznegrin was on it, do we have a tool in mind? 
I suggested Jenkins for scripts/jobs, but unsure about the needs

**Comment by drorgivton** [comment]
Great Job @Sund3 we have the solutions we needed :)
