### ISSUE TITLE
Prepare a plan to migrate our DB from server to RDS

### ISSUE THREAD

**Issue by drorgivton** [meirim-org/meirim#492]

**Comment by Sund3** [comment]
@raznegrin Hey, can I get AWS privileges and a db user so I can view the db and see what we will need for RDS?

**Comment by Sund3** [comment]
Did some digging around, still missing some credentials to actually perform the migration.

Current setup:
EC2 t3.nano -> ~ 4$/month
CPU:2 RAM:0.5GB	Network:Up to 5Gbps

Desired setup:
RDS db.t4g.micro/db.t3.micro -> ~ 12$/month
CPU:2 RAM:1GB	Network:Up to 5Gbps

Additional charges are for storage.

Overall this is the result:

The old setup:
Amazon EC2 Service: $11.88
  Compute:$8.36
  EBS Volumes:$3.52
Free Tier Discount:$-3.30
Cost:$8.58

The NEW setup
Amazon RDS Service: $31.44
  DB instances:$26.36
  Storage:$5.08
Free Tier Discount:$-2.54
Cost: $28.90

~20$ more/month

What will we get? 
1. Twice as much RAM (1GB as to 0.5GB)
2. Managed MySQL, upgrades, maintenance, avialability

@raznegrin thoughts?

**Comment by drorgivton** [comment]
Solved by choosing STRAPI
