### ISSUE TITLE
Change Eyal's Email to INFO

### ISSUE THREAD

**Issue by chechiktomer** [meirim-org/meirim#51]

**Comment by BlueHotDog** [comment]
Can't find where to change..

**Comment by BlueHotDog** [comment]
@chechiktomer ^

**Comment by chechiktomer** [comment]
@eyalmigd 
Eyal, please write down where this Email is written, or what Emails you receive.

10x

**Comment by eyalmigd** [comment]
I think @dortheimer  will know how to answer this

**Comment by dortheimer** [comment]
@BlueHotDog where is this email address displayed?

**Comment by BlueHotDog** [comment]
@dortheimer @eyalmigd @chechiktomer no idea guys, the task says "Change Eyal's Email to INFO" no idea where to take it from here.

**Comment by chechiktomer** [comment]
@eyalmigd  What Emails do you get?
What type of Emails?

**Comment by eyalmigd** [comment]
יש לי את תיבת המייל בZOHO שהיא eyal@meirim. והכוונה היא שנשנה אותה ל
INFO@meirim


2018-03-01 12:41 GMT+02:00 chechiktomer <notifications@github.com>:
