### ISSUE TITLE
Monitor iplan process

### ISSUE THREAD

**Issue by GalGend** [meirim-org/meirim#550]
As we started using the uptime robot as our monitoring tool, we created a new monitor for the iplan process. 
We need to report every time we have finished successfully an iplan process, to the uptime monitor; just a ping request and the success is recorded.

**Comment by yaelal** [comment]
in uptime robot added new monitor called 
"iplan process" of type heartbeat, that means we have a specific url to call from iplan
currently the monitor is not set to send any alerts, Monitoring Interval is set to receive once a day with Grace Period of 12 hrs

in development that url will not be called, added a development config file so we call google.com instead

branch name issue_550

**Comment by yaelal** [comment]
pr https://github.com/meirim-org/meirim/pull/557/files

**Comment by GalGend** [comment]
done
