### ISSUE TITLE
[BE]  support the Block/Parcel Search

### ISSUE THREAD

**Issue by drorgivton** [meirim-org/meirim#558]

**Comment by harshitsan** [comment]
Backend Merge request 
https://github.com/meirim-org/meirim/pull/584

**Comment by harshitsan** [comment]
It's done, once the database is updated on the staging, we can test it.
https://drive.google.com/drive/folders/1eVLbHMF8ljvseqiP6_wYhNU61ray3ngj?usp=sharing [ Link to the SQL file ]
