### ISSUE TITLE
[FE] new homepage search component

### ISSUE THREAD

**Issue by drorgivton** [meirim-org/meirim#559]
1. Replace the existing search component on the homepage, with a new component that lets the user toggle between search by address and search by Block/Parcel
2. Text & Labels should support multi-language translation
3. Block is mandatory, Parcel is optional
4. Proper mobile behavior
5. Validate the input: [0-9] characters; user can only select the suggested values.
6. To submit the search user needs to click the 🔍 button.
7. Parcel field is disabled until user has a valid Block input

[Figma](https://www.figma.com/file/za4s6kKXMHh0X3URWVpXg1/Meirim.org---2022?node-id=8592%3A135338)

![image](https://user-images.githubusercontent.com/66066681/198558400-c308eb82-6703-429e-b18a-9a21f10c3509.png)

**Comment by drorgivton** [comment]
1. Replace the existing search component on the homepage, with a new component that lets the user toggle between search by address and search by Block/Parcel
2. Text & Labels should support multi-language translation
3. Block is mandatory, Parcel is optional
4. Proper mobile behavior
5. Validate the input: [0-9] characters; user can only select the suggested values.
7. To submit the search user needs to click the 🔍 button.
8. Parcel field is disabled until user has a valid Block input
9. [Figma](https://www.figma.com/file/za4s6kKXMHh0X3URWVpXg1/Meirim.org---2022?node-id=8592%3A135338)

<img width="676" alt="image" src="https://user-images.githubusercontent.com/66066681/198558145-55ddcc02-00a1-40fe-bf92-61e9d3f8d7bf.png">

**Comment by harshitsan** [comment]
done, waiting for review
