### ISSUE TITLE
[FE] new Plans page search component

### ISSUE THREAD

**Issue by drorgivton** [meirim-org/meirim#560]
1. Replace the existing search [component](https://www.meirim.org/plans) on the top of the Plans page, with a new component that lets the user toggle between search by address and search by Block/Parcel
2. Text & Labels should support multi-language translation
3. Should accept and populate params when user searched from the Homepage component 
4. _Block_ is mandatory, _Parcel_ is optional
5. Proper mobile behavior
6. Validate the input: [0-9] characters; user can only select the suggested values.
7. Loaders: when fetching suggested results, spinner when user submits the search
8. To submit the search in "Address" mode, user only needs to select and addres
9. To submit the search in "Block/Parcel" mode, user needs to click the 🔍 button.
10. Parcel field is disabled until user has a valid Block input 

[Figma](https://www.figma.com/file/za4s6kKXMHh0X3URWVpXg1/Meirim.org---2022?node-id=8592%3A135338)

**Screenshots**
<img width="548" alt="image" src="https://user-images.githubusercontent.com/66066681/198555264-751068f2-899b-4382-a47d-b061d13e72ec.png">

<img width="943" alt="image" src="https://user-images.githubusercontent.com/66066681/198555597-cd916460-c033-4aa4-ae86-d74de4fcdbbc.png">

**Comment by harshitsan** [comment]
Done, Please review
