### ISSUE TITLE
Import Block and Parcel data to DB

### ISSUE THREAD

**Issue by drorgivton** [meirim-org/meirim#561]
**Blocks** shape file - in [this link](https://data.gov.il/dataset/subgushallshape/resource/f8824746-8e6a-475d-96eb-8c24ceb39a8b/download/sub_gush_all.zip)

**Parcels** shape file - in [this link](https://data.gov.il/dataset/shape/resource/c68b4df6-c809-4bb5-a546-61fa1528fed5/download/parcel_all.zip)

Each parcel has the block number as well in its attribute

**Comment by harshitsan** [comment]
Done
