### ISSUE TITLE
add Ramat Gan trees

### ISSUE THREAD

**Issue by gruppin** [meirim-org/meirim#565]
We wish to scrap the Ramat Gan Tree permit too. 

The permits are published on the following URL: https://www.ramat-[gan.muni.il/tashtiot/view/forest_commissioner/license/2022/](https://www.ramat-gan.muni.il/tashtiot/view/forest_commissioner/license/2023/)

We also wish to allow users to select Ramat Gan from the cities of cities at the My Alert Page

**Comment by gruppin** [comment]
https://www.ramat-gan.muni.il/tashtiot/view/forest_commissioner/license/2022/

**Comment by yaelal** [comment]
branch https://github.com/meirim-org/meirim/tree/issue_565

**Comment by yaelal** [comment]
pr https://github.com/meirim-org/meirim/pull/630/files

**Comment by GalGend** [comment]
@yaelal Happily closing this one
