### ISSUE TITLE
add Beer Sheva trees

### ISSUE THREAD

**Issue by gruppin** [meirim-org/meirim#566]
https://www.beer-sheva.muni.il/residents/environment/pkidyearot/pages/invalidlicense.aspx

need to crawl in 2 phases:
1. get all liecences id.
2. construct url per id according to this format:
https://www.beer-sheva.muni.il/Residents/Environment/PkidYearot//Lists/List/DispForm.aspx?ID=3720

**Comment by yaelal** [comment]
@GalGend @gruppin 
there is also this url
https://www.beer-sheva.muni.il/Residents/Environment/PkidYearot/pages/validlicense.aspx

and in both there are very old licenses
i made a cut by date so we ignore the old
but do we want to use this second url as well?

**Comment by yaelal** [comment]
branch issue_566_beer_sheva_tree

**Comment by gruppin** [comment]
yes, we take as many as we can :)

**Comment by yaelal** [comment]
pr https://github.com/meirim-org/meirim/pull/665
