### ISSUE TITLE
Bug in sharing tree link 

### ISSUE THREAD

**Issue by GalGend** [meirim-org/meirim#571]
When sharing a tree using WhatsApp, a redundant `%` is sent. Needs to fix it.

@gruppin , also WDYT in changing the text to `רשיון כריתת עצים שאולי יעניך אותך` instead of `היתר שאולי יענין אותך`

![image](https://user-images.githubusercontent.com/22238092/200123424-cd222a52-7bb5-4339-84d6-50ef49c69bf2.png)

Also, please make sure this doesn't happen to plans too

**Comment by yaelal** [comment]
https://github.com/meirim-org/meirim/pull/574  not sure how to test, it looked like a simple issue
but if you can show me how to test i'd like to see, thanks

**Comment by GalGend** [comment]
Yes no problem.
Go to /trees page, then select any tree , go to the tree page and click on "share". You should have Whatsapp web open and it redirects to whatsapp
<img width="1383" alt="image" src="https://user-images.githubusercontent.com/22238092/200135651-ff038eaf-5b15-40c0-bc95-52dc2718f038.png">

Yet, in order to test it locally, you need to scrap some trees , so you have in the local DB

**Comment by yaelal** [comment]
i have no trees locally
how do i add?

**Comment by yaelal** [comment]
seems to work
![image](https://user-images.githubusercontent.com/9642870/200136109-d6b1c25c-07f8-429f-b413-29d2e5a71098.png)
unless you want to change the text

**Comment by GalGend** [comment]
Thanks @yaelal ! @gruppin @drorgivton what do you think the wording should be?

**Comment by yaelal** [comment]
btw, i dont know how to scrap some trees, i just added a record directly to the db table

**Comment by GalGend** [comment]
That's completely fine, anyway we rather write a readme for scrapping trees,

**Comment by gruppin** [comment]
hi! looks good! I support change the name to `רשיון כריתת עצים שאולי יעניין אותך`

**Comment by GalGend** [comment]
@yaelal Can you please change the text and we can close this one?? ☺️ ☝️

**Comment by yaelal** [comment]
done
