### ISSUE TITLE
Contributing code to read felled-tree requests for Haifa

### ISSUE THREAD

**Issue by dpelleg** [meirim-org/meirim#575]
[readpdf.zip](https://github.com/meirim-org/meirim/files/9945718/readpdf.zip)

**Comment by dpelleg** [comment]
This is code to read the list of tree-felling permits for Haifa:

https://www.haifa.muni.il/development-and-construction/engineering-administration/uprooting-trees/

I am contributing it to the Meirim project, no strings attached

**Comment by GalGend** [comment]
Closed due to implemented, thank you
