### ISSUE TITLE
Generate digest emails and store at S3

### ISSUE THREAD

**Issue by GalGend** [meirim-org/meirim#583]
**Background:**

We have the digest email sender that is waiting to be released. When we thought of architecture and scale, we realised that as we dispatch email per alert (and not as before, per a plan/ tree) we cannot support that scale.

In production, we stand at around x alerts. We want to dispatch all the alerts a digest email on workdays, during working hour. Yet, in terms of time, it's impossible as there is not enough time to calculate those.

Our solution is to use AWS lambdas to dispatch all the email sends, and a cronjob that prepares the email data. 

**This contains the following:**
- Use existing new_digest_email logic to generate email content per alert.
- Instead of sending the email content (json params) to sendgrid, store it at s3.
The file key should be a combination of the alert id+ date of generation (up to you to decide)

* make sure you create a dir for all digest emails at s3 (prefix) as the buckets are used across all the app.

S3 buckets to use:
Staging/ dev:
stg-service-data-6b3da185 

prod
prd-service-data-c281bf34

Then, a message with the file id should be pushed into an SQS queue

**Comment by yaelal** [comment]
https://www.kindacode.com/article/how-to-easily-generate-a-random-string-in-node-js/
