### ISSUE TITLE
Lambda Runner + SQS set up

### ISSUE THREAD

**Issue by GalGend** [meirim-org/meirim#589]
Follow up for #588 .

We need to set up Lamndas to run, triggered by an S3 file existence. The lambdas should each receive a file (key) parameter and handle it (a separate task). 

This task is to configure lambdas to run, every Sunday- Thursday from 10:00- 19:00, for each file that exists in the S3 bucket (stg/ prd) with the following prefix (----should be completed).

Also, the following config should be injected into the lambdas:
```
templatePass (sendgrid digest key):"",
templates: {
            "digestPlans":""
            }
```

**Comment by schshmuel** [comment]
Hi, would you like that I will implement this issue? I can also do #588 also.

**Comment by yaelal** [comment]
its actually my task, but we are not proceeding with it on purpose
@GalGend did you manage to arrange a meeting for this? thanks

**Comment by GalGend** [comment]
Hi @schshmuel, I updated the task, and now it can be assigned to you. I guess we need to grant you AWS credentials, so reach out and let's talk. I'm available every evening.
@yaelal fyi

**Comment by yaelal** [comment]
it looks exactly the same 
and doesnt answer the questions i raised

**Comment by schshmuel** [comment]
Hi @GalGend, I tried to reach you through LinkedIn. How do you want us to talk?

**Comment by yaelal** [comment]
we decided to go back to s3 trigger for the lambda and add send date for sendgrid
details in ticket 588

**Comment by GalGend** [comment]
resolved as found an alternative solution
