### ISSUE TITLE
Add Haifa trees

### ISSUE THREAD

**Issue by tomers** [meirim-org/meirim#597]
Source file: http://www1.haifa.muni.il/trees/rptPirsum.pdf
Website: https://www.haifa.muni.il/development-and-construction/engineering-administration/uprooting-trees/

# Design:

This solution is based on earlier work by me to parse Haifa's tree felling permits which are published as PDF into an Excel document. The source code is available here: https://github.com/tomers/haifa-tree-felling-permits. This external project will publish a docker image for us to use. The docker image does the download, parse and store actions, and will also allows uploading to a custom S3 bucket (provided the relevenat credentials).

We will run a daily cron job to run this docker (we will always pull the latest version of the docker image), and provide it with parameters to store the output Excel file to our S3 bucket.
We will also store the file in [Athena style partitions](https://docs.aws.amazon.com/athena/latest/ug/partitions.html), so we can have a backup of out files from all our daily runs.

Now that we have the latest Excel file available as a URL, we can use existing framework to download and parse it, using a specific tree permit parsing code for Haifa.

CC @gruppin

**Comment by tomers** [comment]
In order to periodically parse the public PDF from Haifa municipality's website, and store it as Excel file which is parseable from our code, we should periodically (daily) run a cron job which performs the CLI command described in https://github.com/tomers/haifa-tree-felling-permits#quick-start. 
The command requires AWS credentials, and an AWS S3 bucket with appropriate permissions which the output files will be uploaded to (e.g. `haifa-tree-felling-permits`, as in the example  in the Quick Start paragraph).

@gruppin could you please setup this, so we'll have daily Excel file created by `cron`?

**Comment by GalGend** [comment]
Happily closing this one, if you have follow- up issues, please open tickets @gruppin @tomers
