### ISSUE TITLE
Add our github repo +IG to links at footer

### ISSUE THREAD

**Issue by GalGend** [meirim-org/meirim#612]
Add GitHub and instagram to links on footer-  can people know we're there :)

**Comment by Oferlis** [comment]
Hey, I'd love to be assigned to this issue as my first one 👶🏻

**Comment by GalGend** [comment]
Great, go for it. We have the label welcome for issues that can be good for beginning tasks

**Comment by Oferlis** [comment]
PR link: https://github.com/meirim-org/meirim/pull/655

**Comment by GalGend** [comment]
merged, at PR #655 by @Oferlis
