### ISSUE TITLE
Rescrap all plan statuses 

### ISSUE THREAD

**Issue by GalGend** [meirim-org/meirim#613]
As we recently migrated to the new MAVAT website, we wish to scrap the previous plan progress from the new website. Also, we wish to maintain a process that periodically runs on every plan to look for changes. 

A script already exists (called fetchPlanStatus) but not sure it works with the new MAVAT.

This task is to make sure that it works, and if so, make it work in stg so we rescrap all statuses

**Comment by muamichali** [comment]
Related issue: #596

**Comment by muamichali** [comment]
@GalGend: When I worked on #596 I did confirm that fetchPlanStatus works with the new mavat FYI.

**Comment by muamichali** [comment]
@GalGend this in production, right? I think the issue can be closed.
