### ISSUE TITLE
Make Blue Lines adaptations 

### ISSUE THREAD

**Issue by GalGend** [meirim-org/meirim#614]
- MAVAT_SERVICE_ID should be changed from 0 to 1.
- props should be read from lowercase
- on saving it should be upper case
- Check if Blue Line response contains errors (`data.error`)
- adpataions

![image](https://user-images.githubusercontent.com/22238092/209563420-33ad3e8f-4337-428c-bae4-eb056cfd35a9.png)

**Comment by yaelal** [comment]
pr https://github.com/meirim-org/meirim/pull/615

notice we no longer get several fields: STATION, JURSTICTION_CODE, PLAN_COUNTY_CODE, PLAN_AREA_CODE
