### ISSUE TITLE
Run Haifa scraping docker periodically

### ISSUE THREAD

**Issue by tomers** [meirim-org/meirim#619]
Related to #597.

We need to run the Haifa tree permits docker on a daily basis:
```
docker run --pull always --rm -t -v $(pwd):/output -e SCRAPINGBEE_API_KEY=XXXXXXXXXXXXXXX  tomersha/haifa-tree-felling-permits --download --upload --s3-bucket stg-service-tree-6b3da185 --s3-path haifa --proxy-country il
```
Note that SCRAPINGBEE_API_KEY is a secret, and should not be hard-coded in the command. You should use secretsmanager for that.
Also note that the docker outputs a file, and for that we use a docker volume, mapped to /output internally.

CC @Sund3 @GalGend @gruppin

**Comment by GalGend** [comment]
@tomers is this resolved?

**Comment by gruppin** [comment]
@GalGend yes. we run scheduled fargate task in aws
