### ISSUE TITLE
Send email on new Plan Status 

### ISSUE THREAD

**Issue by GalGend** [meirim-org/meirim#637]
Now that we have status updates for all plans, we'd like to inform our users of that.

We'd like to send an email to users in the following case:
- A new major Meirim status is given
- User follows that plan 

The list of Meirim status is in status table.
The list of plan follows is in plan_person. 

We should use the existing email template, with the following content

״הפקדה להתנגדויות ברעננה - מוצקין 28 רעננה״, ״תוכנית הופקדה להתנגדויות ברעננה״ֿ

Same for cancelled/ approved.

**Comment by yaelal** [comment]
@GalGend  can you help?
branch issue_637 i have an issue with the email sending
im getting an error: self signed certificate in certificate chain
