### ISSUE TITLE
Monitor send_emails and send_tree_emails cron jobs

### ISSUE THREAD

**Issue by GalGend** [meirim-org/meirim#715]
Similar to the heartbeat monitor we have for the crons, we want to monitor the status of these two processes. 

Consult with @yaelal on how it's done- basically we send a ping to a URL on uptime robot. We set up a monitor for each job, then call it when the job is successful.

We want to be triggered if after 3 days, none email for trees/ plans was sent.

<img width="561" alt="image" src="https://github.com/meirim-org/meirim/assets/22238092/0c9dc3cf-b5e6-477a-b622-c67a92048e63">

**Comment by yaelal** [comment]
pr https://github.com/meirim-org/meirim/pull/716

**Comment by yaelal** [comment]
make sure we start the monitors in uptime robot once we deploy to prod (currently paused)

**Comment by GalGend** [comment]
closed due to done, thank you @yaelal
