### ISSUE TITLE
Accessibility Declaration link in the Footer

### ISSUE THREAD

**Issue by drorgivton** [meirim-org/meirim#720]
Add a link labeled
`הצהרת נגישות`

to the **first row** of the website's footer , as the **last** item (after הצטרפו למעירים)

<img width="534" alt="image" src="https://github.com/meirim-org/meirim/assets/66066681/9a456e3c-c8ae-468c-a321-3e89c9011488">

Link URL: https://docs.google.com/document/d/1z79ekk39XpI52gGXy5vW0inCqE4OA33BxwaAL7tZYGE/edit?usp=sharing

**Comment by GalGend** [comment]
merged
