### ISSUE TITLE
Add information text and instruction to alert screen

### ISSUE THREAD

**Issue by chechiktomer** [meirim-org/meirim#76]
The Text can be found on:
https://docs.google.com/document/d/1RniWzA57r_HOlVmVTgmU0aoZ4fTzBj1UYFDMAXM7ykk/edit?ts=5b4ce660

**Comment by dortheimer** [comment]
@chechiktomer ,  where should this text be added in the alert screen?

**Comment by eyalmigd** [comment]
This is the text:

בטופס שלפניכם תוכלו להזין את האזור בו תרצו לקבל התראות. כל מה שצריך לעשות הוא להזין כתובת ולבחור את הרדיוס ממנה בו תרצו לקבל התראות. ניתן להזין יותר מכתובת אחת.

ואיך המערכת עובדת? המערכת תשלח לכם התראה אישית לדוא"ל בכל פעם שתכנית חדשה תקלט או שהסטטוס שלה יתעדכן באזור שבחרתם. שימו לב! תכניות בסמכות מקומית נקלטות בדרך כלל במערכת רק בשלב ההפקדה ומתעדכנות בעת אישור התכנית. לעומת זאת, תכניות בסמכות מחוזית נקלטות במערכת לפני הפקדה מתעדכנות כמה פעמים לאורך הדרך. ז"א, סביר מאוד להניח שתקבלו יותר משתי התראות על תכנית בסמכות מחוזית. המערכת מסונכרנת מידי לילה כך שעל פי רוב, אם תכנית הופקדה היום, נקבל על כך התראה רק ביום למחרת. 

בהצלחה! החברים מ"מעירים"

**Comment by dortheimer** [comment]
Resolved
