### ISSUE TITLE
Problem with service 

### ISSUE THREAD

**Issue by eyalmigd** [meirim-org/meirim#85]
התכנית שבלינק המצורף נשלחה אלי במייל בתאריך 18.10.18. כשלא ברור בכלל למה. הסטטוס שלה הוא "ממתינה להחלטה בהפקדה" אבל במעבר על דף מסמכי התכנון של מנהל התכנון לא היה דיון כלשהו בתכנית בימים הסמוכים. 

[](https://meirim.org/plan/?id=12235)

**Comment by eyalmigd** [comment]
[https://meirim.org/plan/?id=12235](url)

**Comment by dortheimer** [comment]
ישלח רק בעדכון סטטוס
