### ISSUE TITLE
Problem with service #2

### ISSUE THREAD

**Issue by eyalmigd** [meirim-org/meirim#86]
בדף התכנית שבלינק הזה (גם בנק החקלאות) מופיע תאריך ההפקדה כלמעשה התכנית עוד לא הופקדה. ע"פ דף מסמכי התכנון של מנהל התכנון זה תאריך בו התקיים דיון "החלטה בדיון בהפקדה" - זה יום שבו החליטו להפקיד את התכנית בכמה תנאים אבל בפועל היא עוד לא הופקדה.

[https://meirim.org/plan/?id=12235](url)

**Comment by dortheimer** [comment]
הוסר התאריך
