### ISSUE TITLE
Calculate days for objection submission

### ISSUE THREAD

**Issue by eyalmigd** [meirim-org/meirim#89]
מאוד חשוב שבמידה והתכנית הופקדה יהיה איזה חישוב לאחור של הימים הנותרים להפקדה. זה יכול להיות גם במייל באדום (כדי להלחיץ) וחייב להופיע בבירור בדף התכנית שלנו. עושים את זה בתב"ע פתוחה וזה נפלא

**Comment by florpor** [comment]
cleaning old issues
